# Generated by Django 3.2.6 on 2021-08-16 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('shortdescription', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
                ('icon', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='M_SubServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('shortdescription', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
                ('icon', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('MainService', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.m_services')),
            ],
        ),
    ]
