# Generated by Django 3.2.6 on 2021-08-17 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_m_services_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_subservices',
            name='MainService',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='mainApp.m_services'),
        ),
        migrations.CreateModel(
            name='RServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=1000)),
                ('address', models.TextField()),
                ('location', models.TextField()),
                ('contact', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('MainService', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='mainApp.m_subservices')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
