# Generated by Django 3.2.6 on 2021-08-17 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20210817_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rservices',
            old_name='contact',
            new_name='time',
        ),
    ]
