# Generated by Django 3.2.6 on 2021-08-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_rename_contact_rservices_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='rservices',
            name='ServiceDate',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
